# Generated by Django 6.0.7 on 2026-07-17 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('tournaments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='users.person'),
        ),
        migrations.AddField(
            model_name='playeraward',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_awards', to='players.award'),
        ),
        migrations.AddField(
            model_name='playeraward',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='players.player'),
        ),
        migrations.AddField(
            model_name='playeraward',
            name='tournament_edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_awards', to='tournaments.tournamentedition'),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='players.playerstatus'),
        ),
        migrations.AddField(
            model_name='team',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_for_teams', to='users.person'),
        ),
        migrations.AddField(
            model_name='team',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='tournaments.sponsor'),
        ),
        migrations.AddField(
            model_name='teamparticipation',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_for_participations', to='users.person'),
        ),
        migrations.AddField(
            model_name='teamparticipation',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='tournaments.sponsor'),
        ),
        migrations.AddField(
            model_name='teamparticipation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='players.team'),
        ),
        migrations.AddField(
            model_name='teamparticipation',
            name='tournament_edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_participations', to='tournaments.tournamentedition'),
        ),
        migrations.AddField(
            model_name='playeraward',
            name='team_participation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_awards', to='players.teamparticipation'),
        ),
        migrations.AddField(
            model_name='teamparticipationplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='players.player'),
        ),
        migrations.AddField(
            model_name='teamparticipationplayer',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participation_players', to='players.playerstatus'),
        ),
        migrations.AddField(
            model_name='teamparticipationplayer',
            name='team_participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='players.teamparticipation'),
        ),
        migrations.AddField(
            model_name='teamparticipation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='players.teamstatus'),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='players.teamstatus'),
        ),
        migrations.AlterUniqueTogether(
            name='teamparticipationplayer',
            unique_together={('team_participation', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='teamparticipation',
            unique_together={('team', 'tournament_edition')},
        ),
    ]
