# Generated by Django 6.0.7 on 2026-07-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='contract_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='current_club',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='player',
            name='secondary_position',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
