# Generated by Django 6.0.7 on 2026-07-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_person_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('', 'Unspecified')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to='persons/photos/'),
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
