# Generated by Django 6.0.7 on 2026-07-17 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_person_profile_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code, e.g. SLO",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "iso2",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 for flag icons, e.g. SI",
                        max_length=2,
                        unique=True,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["order", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="person",
            name="nationality",
        ),
        migrations.AddField(
            model_name="person",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="persons",
                to="users.country",
            ),
        ),
    ]
