# Generated by Django 6.0.7 on 2026-07-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_country_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso2',
            field=models.CharField(help_text='Flag code for country-flag-icons, e.g. SI or GB-ENG', max_length=10, unique=True),
        ),
    ]
