# Generated by Django 6.0.7 on 2026-07-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField(blank=True, null=True)),
                ('match_date', models.DateTimeField(blank=True, null=True)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('halftime_home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('halftime_away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_time_home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_time_away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('home_score_penalties', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score_penalties', models.PositiveIntegerField(blank=True, null=True)),
                ('is_extra_time', models.BooleanField(default=False)),
                ('is_penalties', models.BooleanField(default=False)),
                ('is_walkover', models.BooleanField(default=False)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('extra_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('half', models.CharField(max_length=20)),
                ('goal_type', models.CharField(blank=True, max_length=30)),
                ('body_part', models.CharField(blank=True, max_length=20)),
                ('is_penalty', models.BooleanField(default=False)),
                ('is_own_goal', models.BooleanField(default=False)),
                ('is_var_decision', models.BooleanField(default=False)),
                ('var_result', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('score_home_at_event', models.PositiveIntegerField(blank=True, null=True)),
                ('score_away_at_event', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['minute', 'extra_minute', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Match statuses',
                'ordering': ['order'],
            },
        ),
    ]
