# Generated by Django 6.0.7 on 2026-07-17 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0002_initial'),
        ('players', '0001_initial'),
        ('tournaments', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refereed_matches', to='users.person'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournamentphase'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_phase_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.tournamentphasegroup'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='matches.eventtype'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='players.player'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='related_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_events', to='players.player'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='team_participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='players.teamparticipation'),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='matches.matchstatus'),
        ),
    ]
