# Generated by Django 6.0.7 on 2026-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='is_temporary_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='temporary_player_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
