# Generated by Django 6.0.7 on 2026-07-17 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_initial'),
        ('tournaments', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_for_tournaments', to='users.person'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='tournaments.sponsor'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.sport'),
        ),
        migrations.AddField(
            model_name='tournamentedition',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_for_editions', to='users.person'),
        ),
        migrations.AddField(
            model_name='tournamentedition',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_editions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentedition',
            name='global_rule_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editions', to='tournaments.globalruletemplate'),
        ),
        migrations.AddField(
            model_name='tournamentedition',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='tournaments.sponsor'),
        ),
        migrations.AddField(
            model_name='tournamentedition',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentfinalstanding',
            name='team_participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_standings', to='players.teamparticipation'),
        ),
        migrations.AddField(
            model_name='tournamentfinalstanding',
            name='tournament_edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_standings', to='tournaments.tournamentedition'),
        ),
        migrations.AddField(
            model_name='tournamentphase',
            name='tournament_edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='tournaments.tournamentedition'),
        ),
        migrations.AddField(
            model_name='tournamentphasegroup',
            name='tournament_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.tournamentphase'),
        ),
        migrations.AddField(
            model_name='tournamentphasegroupteam',
            name='team_participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='players.teamparticipation'),
        ),
        migrations.AddField(
            model_name='tournamentphasegroupteam',
            name='tournament_phase_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_teams', to='tournaments.tournamentphasegroup'),
        ),
        migrations.AddField(
            model_name='tournamentprize',
            name='player_award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes', to='players.playeraward'),
        ),
        migrations.AddField(
            model_name='tournamentprize',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes', to='tournaments.sponsor'),
        ),
        migrations.AddField(
            model_name='tournamentprize',
            name='team_participation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes', to='players.teamparticipation'),
        ),
        migrations.AddField(
            model_name='tournamentprize',
            name='tournament_edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='tournaments.tournamentedition'),
        ),
        migrations.AddField(
            model_name='tournamentedition',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='tournaments.tournamentstatus'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentfinalstanding',
            unique_together={('tournament_edition', 'team_participation')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentphasegroupteam',
            unique_together={('tournament_phase_group', 'team_participation')},
        ),
    ]
