# Generated by Django 6.0.7 on 2026-07-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentphase',
            unique_together={('tournament_edition', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentphasegroup',
            unique_together={('tournament_phase', 'name')},
        ),
    ]
