# Generated by Django 6.0.7 on 2026-07-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_format_and_phases'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalruletemplate',
            name='max_team_fouls',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalruletemplate',
            name='points_for_draw',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='globalruletemplate',
            name='points_for_win',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
