# Generated by Django 6.0.7 on 2026-07-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_global_rule_template_points_fouls'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalruletemplate',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Built-in seed template; cannot be deleted by users.'),
        ),
    ]
