# Generated by Django 6.0.7 on 2026-07-20 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_category_and_rule_template_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentFormatConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_groups', models.PositiveSmallIntegerField(default=4)),
                ('teams_per_group', models.PositiveSmallIntegerField(default=4)),
                ('teams_advancing_per_group', models.PositiveSmallIntegerField(default=2)),
                ('best_runners_up', models.BooleanField(default=False)),
                ('number_of_best_runners_up', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ranking_criteria', models.JSONField(blank=True, default=list, help_text='Ordered list, e.g. ["points","goal_difference","goals_for","head_to_head"]')),
                ('half_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('half_time_break_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('buffer_between_matches_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('has_third_place_match', models.BooleanField(default=True)),
                ('pairing_method', models.CharField(choices=[('auto_cross', 'Auto cross (A1–B2, A2–B1, …)'), ('manual', 'Manual pairing')], default='auto_cross', max_length=20)),
                ('knockout_home_advantage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament_edition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='format_config', to='tournaments.tournamentedition')),
            ],
            options={
                'verbose_name': 'Tournament format config',
                'verbose_name_plural': 'Tournament format configs',
            },
        ),
    ]
